### PR TITLE
removed iframe/page type check from HTTP requests

### PR DESCRIPTION
**Pull request by LilyLME**
Removed is_full_page and is_frame_load in http_requests as prescribed in  #565

### CODE REVIEW

**Comment by LilyLME** [comment]
@englehardt I bet we have to take that off the documentation as well?

**Comment by englehardt** [comment]
> @englehardt I bet we have to take that off the documentation as well?

Yes, thanks for the reminder. I can do that when we merge.

I think you're almost there! You just have a few test failures to fix (see: https://travis-ci.org/github/mozilla/OpenWPM/jobs/664536322#L2602). The problem here is that the hard coded records expected by the test page still contain values for the `is_full_page`/`is_frame_load` columns. You'll need to remove those as well.

**Comment by LilyLME** [comment]
Got the tests to pass! After a while of missing just one uncorrected row in the HTTP_REQUEST dict. {} :/

Screenshot from 2020-03-22 02-21-54

**Comment by LilyLME** [comment]
@englehardt Please do have a look again.

**Comment by englehardt** [comment]
This looks good to me, thank you!

**Comment by englehardt** [comment]
I've updated the wiki as well.

**Comment by englehardt** [comment]
@skim1112 do you also want to look this over?

**Comment by LilyLME** [comment]
Great.

**Pull request merged**
