### PR TITLE
Making memory_watchdog not run by default

### LINKED ISSUE #778: OpenWPM Watchdog Error
When ever I try to run demo.py, openwpm-watchdog gives the following error:
```Exception in thread OpenWPM-watchdog:
Traceback (most recent call last):
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/_psosx.py", line 484, in memory_full_info
    uss = cext.proc_memory_uss(self.pid)
PermissionError: [Errno 13] Access denied (originated from task_for_pid)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ankushdua/Documents/GitHub/OpenWPM/automation/TaskManager.py", line 240, in _manager_watchdog
    mem_bytes += child.memory_full_info().uss
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/__init__.py", line 1094, in memory_full_info
    return self._proc.memory_full_info()
  File "/Users/ankushdua/opt3/anaconda3/envs/openwpm/lib/python3.8/site-packages/psutil/_psosx.py", line 349, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=15450)
```

Operating System - MacOS 10.15.7

### PR DESCRIPTION
**Pull request by ankushduacodes**
Running test to fix #778

### CODE REVIEW

**Comment by vringar** [comment]
Thanks for this PR.
Could you please also change `demo.py` to set `memory_watchdog` to true?

**Comment by vringar** [comment]
Thank you for adding the docs. Could you also make `process_watchdog` also a `manager_param`?

**Comment by ankushduacodes** [comment]
> Thank you for adding the docs. Could you also make `process_watchdog` also a `manager_param`?

Do you want me to make it manager_param in this branch or do you want me to start a new pull request? or may be could do it  while resolving #749

**Comment by vringar** [comment]
> Do you want me to make it manager_param in this branch or do you want me to start a new pull request? or may be could do it while resolving #749

You're right it doesn't belong in this PR.

**Review by vringar — APPROVED** [review]

**Comment by vringar** [comment]
Do you have anything you want to add to this PR? Otherwise I'm merging this

**Comment by ankushduacodes** [comment]
> Do you have anything you want to add to this PR? Otherwise I'm merging this

Everything is Okay from my side, Please go ahead and merge it 🚀

**Pull request merged**
