### PR TITLE
Restored travis for webext-instrumentation

### PR DESCRIPTION
**Pull request by motin**
Restored a version of the webext-instrumentation for travis (originally dropped in 49078b3b219da4b847e775f7ab095f437639e66e)

### CODE REVIEW

**Comment by motin** [comment]
@englehardt Hmm, where is that? I see no errors in Travis for the latest build.

**Comment by englehardt** [comment]
@motin it's hidden by a fold on the ` npx nyc report --reporter=lcov | npx codecov` command. It doesn't actually throw an error code, so travis doesn't complain.

```
1.40s$ npx nyc report --reporter=lcov | npx codecov
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.5.0
==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{
  commit: '7b353fe22ceb890adc37e3a46bae6a1b55365fb4',
  branch: 'master',
  package: 'node-v3.5.0'
}
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/mozilla/OpenWPM -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    X Failed to read file at 
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/mozilla/OpenWPM/commit/1cf4c9d1776cdb49ad090561de5f63d39460cfb4
```

**Comment by motin** [comment]
@englehardt Thanks, that was well spotted :) - now inactivated until further notice

**Comment by englehardt** [comment]
I'm pretty sure these Travis errors are coming as a result of the unbranded build moving to Firefox 68. There must be some change in the way we're handling profiles, specifically `webappstore.sqlite`. This will have to be fixed in another PR.

We should figure out how to manage Firefox versions properly with the unbranded build. Updates to the next release version should be gated on a PR from us, but it's not clear to me that's possible with the link we're currently using to download the binaries (as it doesn't have version information in it). We should also check the currently installed Firefox version and warn the user if it's out of date for whatever version of OpenWPM they've checked out.

**Comment by englehardt** [comment]
I filed https://github.com/mozilla/OpenWPM/issues/381 to track the install version.

**Pull request merged**
