### PR TITLE
Npm publishing routines for instrumentation prepared

### LINKED ISSUE #337: Define versioning and npm publishing routines
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I propose some guidelines:
* Version bumps should be done directly in the master branch (not via PRs), preferably using https://www.npmjs.com/package/standard-version
* Versioning should follow [semver](https://semver.org/)
* Version bumps should be followed by a npm publish, preferably using https://www.npmjs.com/package/publish-please

* **Other information**
Proposed publish-please configuration:
```
{
  "validations": {
    "vulnerableDependencies": true,
    "uncommittedChanges": true,
    "untrackedFiles": true,
    "sensitiveData": true,
    "branch": "master",
    "gitTag": true
  },
  "confirm": true,
  "publishCommand": "npm publish",
  "publishTag": "latest",
  "prePublishScript": "npm test",
  "postPublishScript": false
}
```

### PR DESCRIPTION
**Pull request by motin**
Fixes #337
Enables https://github.com/mozilla/OpenWPM/issues/329

This configures standard-version and publish-please according to https://github.com/mozilla/OpenWPM/issues/337, except for `"gitTag": true` which is currently set to `"gitTag": false` pending upstream merge/accept of https://github.com/inikulin/publish-please/pull/90 (which in turn allows us to use `"gitTag": "webext-instrument/v"` so that we can continue prefixing the instrumentation git tags as per our monorepo setup.)

Example output after instrumentation tests have run:
```
Running validations
-------------------------
✓ Checking for the vulnerable dependencies
✓ Checking for the uncommitted changes
✓ Checking for the untracked files
✓ Checking for the sensitive and non-essential data in the npm package
✓ Validating branch

-------------------
👍 👍 👍

Release info
-------------------------
  Version:       0.3.0
  Latest commit: 68f799a Tmp to test
  Publish tag:   latest
  Publisher:     motin
? Are you sure you want to publish this version to npm? y/N
```

Actual publishing can be done first after this has been merged, since publishing should always be done from the master branch, synced with a corresponding git tag etc.

### CODE REVIEW

**Comment by englehardt** [comment]
Overall this looks good, but I'm not very familiar with npm. I'd like to get @nhnt11's opinion.

**Comment by motin** [comment]
@englehardt Any idea why CI keeps failing? It does not seem to be related to the webext-instrumentation

**Comment by motin** [comment]
I rebased this on the latest master in order to have Travis validate this PR before merge.

**Comment by motin** [comment]
@englehardt This is now ready for merge from my side, pending your review. I added docs describing how the publishing is performed in https://github.com/mozilla/OpenWPM/pull/373/files#diff-146715d709cb252b0edf718157333b49R28

**Pull request merged**
