### PR TITLE
Converted TSLint to ESLint

### PR DESCRIPTION
**Pull request by Ayushsunny**
Move from tslint to eslint #928

Here's the screenshot of what I'm getting after moving.
Screenshot from 2021-05-19 17-31-04

### CODE REVIEW

**Comment by Ayushsunny** [comment]
Hello @vringar Could you review please.

**Comment by vringar** [comment]
Could you please remove tslint from the `package.json` and replace it with eslint where appropriate.

**Comment by Ayushsunny** [comment]
> Could you please remove tslint from the `package.json` and replace it with eslint where appropriate.

@vringar Done.

**Comment by vringar** [comment]
Thank you!
Could you make sure that `npm run fix:eslint` and `npm run test:lint` run without any errors.

**Comment by Ayushsunny** [comment]
I am getting this error after running `npm run fix:eslint`

Screenshot from 2021-05-21 05-42-11

**Comment by vringar** [comment]
Have you run `npm install` after changing the dependencies?
Maybe the required packages just aren't installed. If that doesn't work I'd suggest searching for "Error: Cannot find module optionator eslint"

**Comment by Ayushsunny** [comment]
> Have you run `npm install` after changing the dependencies?
> Maybe the required packages just aren't installed. If that doesn't work I'd suggest searching for "Error: Cannot find module optionator eslint"


Sir, after running `npm install` and changing eslint code in package.json it's throwing errors again -

Screenshot from 2021-05-22 08-13-31

**Comment by vringar** [comment]
I'm assuming this is because the CLI parameters are slightly different between ESLint and TSLint.

By running `npx eslint --help` and looking at the [CLI docs for TSLint](https://palantir.github.io/tslint/usage/cli/)  you should be able to approximately convert between the two commands.

**Comment by Ayushsunny** [comment]
> I'm assuming this is because the CLI parameters are slightly different between ESLint and TSLint.
> 
> By running `npx eslint --help` and looking at the [CLI docs for TSLint](https://palantir.github.io/tslint/usage/cli/) you should be able to approximately convert between the two commands.


Hello @vringar 
Sir, Can you check the new amended commit.

**Comment by vringar** [comment]
Now when running `npm run lint` I get an error that reads:
```
ESLint: 7.27.0

Error: Cannot read config file: /run/media/stefan/02e400c2-1bdd-4d46-a0dd-044d6b4f3af4/Projekte/work/OpenWPM/openwpm/Extension/webext-instrumentation/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

```

Can you check what this is about and make the necessary adjustments?

**Comment by vringar** [comment]
Btw in case this wasn't clear. I really appreciate you sticking with this project and PR for so long.
I can imagine this being pretty frustrating. Thank you!

**Comment by Ayushsunny** [comment]
> Btw in case this wasn't clear. I really appreciate you sticking with this project and PR for so long.
> I can imagine this being pretty frustrating. Thank you!


Yes @vringar It's so frustrating that for some small issue that I'm not able to find out making trouble to run lint.
I'm really sorry for the late responses and also I'm trying my best to do it.
Thank you so much for helping me.

**Comment by vringar** [comment]
Please don't feel any pressure or rush to get this done from my side!
I was hoping this would be significantly easier so I appreciate your continued effort a lot.

**Comment by Ayushsunny** [comment]
Hello @vringar Sir, How you doin' ?
I've finished all of my Uni tests now I'm free to work. can I start again with this issue or some other one?

**Comment by vringar** [comment]
Hey @Ayushsunny,

I'm doing well, how are you? 
Glad to hear you finished your tests and I hope they went well.

If you want to keep working on this I'm very thankful but could also understand that you want to work on something else for a bit.
If you need a break from this PR have a look at #904. The folks at readthedocs.org recently switched us from conda to mamba and maybe that allows us to remove this work-around.

**Comment by vringar** [comment]
Hey,
i fixed the remaining issues with this PR in #940 however I seem to have broken the extension while applying some of the suggested fixes.
Thank you so much for the work you have done here!

**Pull request closed without merging**
