### PR TITLE
Pre commit hooks

### LINKED ISSUE #633: Addition of pre-commit hooks
While working on the codebase, if the changes are pushed without checking the linting issue, may fail the Travis build, and thus causing manual error checking and again running the lint. This is a tedious task for a programmer and may forget to do that.
So, we can work with pre-commit hooks, as it will run all the required linting tests before the commit itself.
I implemented this in the Treeherder repo, and it works smooth!

### PR DESCRIPTION
**Pull request by shubhank-saxena**
This fixes #633 
@vringar
- I have added pre-commit hooks
- Have added flake8,isort and shellcheck(as project contains lot of shell scripts)
- Updated the docs
Let me know if any further changes are required

### CODE REVIEW

**Comment by vringar** [comment]
Could you add `pre-commit` to `requirements-dev.in` and make `autopep8` part of the pre-commit hook to run before `flake8`

**Comment by vringar** [comment]
Do the hooks run in any order or in parallel? Because if they run in order isort should be happening before flake8 right?
Because I only use autopep8 and isort to actually fix issues and flake8 to warn me.
What the shell script version of this would be is
```bash
autopep8 --in-place
isort -y
flake8
```

**Comment by vringar** [comment]
Or did you want them all to be just linting and make the developer fix these issues manually?

**Comment by shubhank-saxena** [comment]
> Or did you want them all to be just linting and make the developer fix these issues manually?

Some of the changes are to be warned which is to be fixed manually. Also, they do run in sequence. I suspect a minor tweak in setup.cfg is required to enforce our settings as isort pre-commit hook behaves little strange!

**Comment by vringar** [comment]
When trying to run `pre-commit run` I got an error. I've attached the log
[pre-commit.log](https://github.com/mozilla/OpenWPM/files/4592547/pre-commit.log)
I don't quite understand what this error means but it seems like it's trying to checkout out OpenWPM at tag `1.5.2` and not autopep8

**Comment by shubhank-saxena** [comment]
> When trying to run `pre-commit run` I got an error. I've attached the log
> [pre-commit.log](https://github.com/mozilla/OpenWPM/files/4592547/pre-commit.log)
> I don't quite understand what this error means but it seems like it's trying to checkout out OpenWPM at tag `1.5.2` and not autopep8

It was failing to pickup the autopep8 version. So I added a "v" tag to mention the version. Should work now!

**Comment by vringar** [comment]
Could you replace the `flake8` command in the `.travis.yml` with `pre-commit run` so our hooks also run server-side?

**Comment by shubhank-saxena** [comment]
Facing a very strange error when I am trying to compile the file, I am getting timeout error :face_with_head_bandage:

**Comment by vringar** [comment]
That's indeed quite curios. Will try to reproduce locally and set you a PR if I can get it to run

**Comment by vringar** [comment]
I've opened [a PR against your repo](https://github.com/shubhank-saxena/OpenWPM/pull/1)

**Comment by shubhank-saxena** [comment]
@vringar everything is working as expected! These are some shellchecks error. Do you want me to fix them in this PR itself or maybe we can raise another PR just for shellchecks?

**Pull request merged**
