### PR TITLE
Make CI error out if our tests aren't passing

### LINKED ISSUE #707: CI can fail but show as green :(
See build:

https://travis-ci.org/github/mozilla/OpenWPM/jobs/706059232

The tests failed spectacularly but because the codecov ran and exited with a 1. The tests showed as passing.

### PR DESCRIPTION
**Pull request by vringar**
Closes #707

### CODE REVIEW

**Comment by vringar** [comment]
Okay, so as long as this isn't all collapsed into one line it's valid bash but once Travis smooshes it together it no longer works.

**Comment by birdsarah** [comment]
Can you add a commit where the tests fail?

**Comment by vringar** [comment]
[This is a PR that should fail](https://github.com/mozilla/OpenWPM/pull/727) as the tests need to be adjusted.

**Comment by birdsarah** [comment]
I'm confused. The tests in that PR are passing. As in, if I go and look at the travis logs, the tests are passing.

**Comment by birdsarah** [comment]
Can we just make this PR self contained. You add a deliberate fail, and then reverse it.

**Comment by vringar** [comment]
Added the failing test

**Comment by birdsarah** [comment]
Sweet! r+ from me when the failing test is reversed.

**Pull request merged**
