### PR TITLE
Command refactoring

### PR DESCRIPTION
**Pull request by cyruskarsan**
refactored dump page source and recursive page source dump
@vringar please review

### CODE REVIEW

**Comment by vringar** [comment]
This PR is currently blocked by `isort` failing.
Are you using `pre-commit` or is there something that makes you not use the tool?
I'm genuinely curious, because I quite like it, so I'm curious if there are any problems with it, that I'm not aware of.

**Comment by cyruskarsan** [comment]
@vringar I am not using `pre-commit`. I'm not sure what is wrong because in `demo.py` I've added calls to all the functions I've refactored and it seems to be working.

**Comment by vringar** [comment]
Sorry for the bad phrasing.
Isort is another tool we are using to keep our code looking uniform just like black. It sorts imports.
And just like black if the code isn't formatted as expected it will fail our CI.
From reading the code I'd expect it to do the right thing, so I'll merge it as soon as the imports are sorted and the CI is passing.

**Comment by cyruskarsan** [comment]
@vringar Ah understood, thank you! I've formatted the files using isort

**Comment by cyruskarsan** [comment]
It looked like isort failed again. This time, I formatted every file it recommended to me instead of just the files I had modified.

**Review by vringar — APPROVED** [review]

**Comment by vringar** [comment]
Hmm, interesting. Seeing as this isn't going to get merged into master and I don't know why isort isn't picking up on the config we have set in  `setup.cfg` I'm just going to merge this and reformat it myself once we have ported all of the commands and want to merge #750

**Pull request merged**
