### PR TITLE
Update all request_id types to integer.

### PR DESCRIPTION
**Pull request by richardgreg**
Fixes: #748

Signed-off-by: Richard O. Gregory <richardgrecoson@gmail.com>

### CODE REVIEW

**Comment by vringar** [comment]
Hey, thanks for working on this.
This looks really good, but you also need to change the typescript definitions, which can be found [here](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/webext-instrumentation/src/schema.ts)

**Comment by richardgreg** [comment]
@vringar changing the values in the ts schema seems to break the application. Or am I the one changing the wrong values?

**Comment by vringar** [comment]
@richardgreg No, you aren't changing the wrong values, but since this is typescript you'll need to change the upstream types as well.
To quickly see where you need to change stuff, I'd suggest running `npm install` in the `automation/Extension//webext-instrumentation` folder.
Then npm should tell you all the places where you need to adjust the types.

**Comment by richardgreg** [comment]
@vringar could you explain the errors to me?

**Comment by vringar** [comment]
@richardgreg I'm looking into it. Will run the tests locally and try to get some more usable error messages.

**Comment by vringar** [comment]
Hmm, apparently localstack is complaining that there aren't any buckets, the only reason this could happen, is because we aren't saving anything out to localstack, which I can't imagine but need to investigate.
Sorry that this turned out to be more complicated than anticipated.

**Comment by richardgreg** [comment]
No problem. I'm happy to be working on it.

**Comment by vringar** [comment]
I'm disabling the localstack tests for now, as I can't find a fix. This means you'll have to merge the master branch into your branch once #756 gets merged.
However these tests were the only thing making sure that our parquet schemas are working, so I need to figure out a way to how test your changes without using localstack.

**Comment by richardgreg** [comment]
Alright.

**Review by vringar — APPROVED** [review]
Thanks for doing this!
It looks good to me and I'll test it locally tomorrow before merging it.

**Comment by vringar** [comment]
Turns out I'm wrong and the [WebExtension API still exposes requestId as a string](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders#details), so we need to convert them in our extension code.
I'm going to fix this myself and then merge this.

**Comment by richardgreg** [comment]
Hi @vringar, sorry I a have not had time to work on this issue. I got into the outreachy program and I'm busy with that at the moment.

**Comment by vringar** [comment]
@richardgreg Congrats on the outreachy internship and best of luck with it!

**Comment by vringar** [comment]
Closing this in favour of #765 as a minor change needed to be made.

**Pull request closed without merging**
